apiVersion: apps/v1
kind: Deployment
metadata:
  name: petapp-deployment
  #namespace: petapp
  namespace: default
  labels:
    app: petapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petapp
  template:
    metadata:
      labels:
        app: petapp
    spec:
      containers:
      - name: petapp
        image: gayathrirudra/petapp:1e67984cd62de5ecbba736c5ed46a45983de4985
        ports:
        - containerPort: 8080
